paths:
  video_directory: /home/
  save_directory: /home/
  minian_path: '.'
save_minain:
  meta_dic:
    session: -1
    animal: -1
  overwrite: True

param_load_video:
  pattern: '*.avi'
  downsample:
    frame: 1
    height: 1
    width: 1
  dtype: uint8
  downsample_strategy: subset

clean_up:
  remove_int_folder: False
  save_MC_video: False
  
param_background_removal:
  method: tophat
  wnd: 10

param_estimate_motion:
  dim: frame

#also known as param_subset_mc
param_crop_motion_correct: 
  height: [63.51875000000004, 526.71875, None]
  width: [82.68124999999998, 547.08125, None]

param_denoise:
  method: median
  ksize: 3

param_cluster:
  minian_workers: 10
  memory_limit: 5GB
  threads_per_worker: 2

param_update_temporal:
  iteration:
    1:
      noise_freq: 0.02
      sparse_penal: 1
      p: 1
      add_lag: 20
      jac_thres: 0.2
      background_update: True
    2:
      noise_freq: 0.02
      sparse_penal: 1
      p: 1
      add_lag: 20
      jac_thres: 0.4
      background_update: True

param_get_noise:
  noise_range: [0.06, 0.5]

param_pnr_refine:
  noise_freq: 0.02
  thres: 1

param_ks_refine:
  sig: 0.05

param_seeds_init:
  wnd_size: 1000
  method: "rolling"
  stp_size: 500
  max_wnd: 15
  diff_thres: 3.5

param_seeds_merge:
  thres_dist: 10
  thres_corr: 0.8
  noise_freq: 0.02

param_init_merge:
  thres_corr: 0.8

param_initialize:
  thres_corr: 0.8
  wnd: 10
  noise_freq: 0.06

param_unit_merge:
  iteration:
    #can use this in place of param_init_merge
    0: 
      thres_corr: 0.8
    1:
      thres_corr: 0.8

param_update_spatial:
  iteration:
    1:
      dl_wnd: 10
      sparse_penal: 0.01
      size_thres: [25, ~]
      background_update: True
    2:
      dl_wnd: 10
      sparse_penal: 0.01
      size_thres: [25, ~]
      background_update: True